[package]
name = "doip-codec"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.4"
tokio = { version = "1.42.0", features = ["full"] }
tokio-util = {version = "0.7.13", features = ["full"]}
