[package]
name = "doip-codec"
version = "2.0.2"
authors = ["Samuel Preston <samp.reston@outlook.com>"]
edition = "2021"
description = "Diagnostics over Internet Protocol codec for client-server communication."
readme = "README.md"
repository = "https://github.com/samp-reston/doip-codec"
license = "MIT"
keywords = ["doip", "diagnostics", "vehicle", "codec"]
categories = [
  "simulation",
  "parser-implementations",
  "network-programming",
  "encoding",
]

[dependencies]
doip-definitions = "1.0.0"
thiserror = "2.0.9"
tokio-util = { version = "0.7.13", features = ["codec"] }

[dev-dependencies]
tokio = { version = "1.42.0", features = ["rt", "macros"] }
futures = "0.3.31"

[profile.release]
strip = true      # Automatically strip symbols from the binary.
lto = true
codegen-units = 1
