[package]
name = "doip-codec"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.31"
thiserror = "2.0.4"
tokio = { version = "1.42.0", features = ["full"] }
tokio-stream = "0.1.17"
tokio-util = {version = "0.7.13", features = ["full"]}
