[package]
name = "doip-codec"
version = "2.0.2"
authors = ["Samuel Preston <samp.reston@outlook.com>"]
edition = "2021"
description = "Diagnostics over Internet Protocol codec for client-server communication."
readme = "README.md"
repository = "https://github.com/samp-reston/doip-codec"
license = "MIT"
keywords = ["doip", "diagnostics", "vehicle", "codec"]
categories = [
  "simulation",
  "parser-implementations",
  "network-programming",
  "encoding",
]

[dependencies]
doip-definitions = "2.0.1"
thiserror = "2.0.11"
tokio-util = { version = "0.7.13", features = ["codec"] }
tokio = { version = "1.43.0", features = ["rt-multi-thread", "macros", "net"] }

[dev-dependencies]
futures = "0.3.31"
