[package]
name = "doip-codec"
version = "2.0.2"
authors = ["Samuel Preston <samp.reston@outlook.com>"]
edition = "2021"
description = "Diagnostics over Internet Protocol codec for client-server communication."
readme = "README.md"
repository = "https://github.com/samp-reston/doip-codec"
license = "MIT"
keywords = ["doip", "diagnostics", "vehicle", "codec"]
categories = [
  "simulation",
  "parser-implementations",
  "network-programming",
  "encoding",
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[profile.test]
panic = "abort"

[dependencies]
doip-definitions = { version = "3.0.4", default-features = false }
heapless = "0.8.0"
thiserror = { version = "2.0.12", default-features = false }

[dev-dependencies]
futures = "0.3.31"
doip-definitions = { version = "3.0.4" }

[features]
default = ["std"]
std = []
