[package]
name = "doip-codec"
version = "1.0.0"
authors = ["Samuel Preston <samp.reston@outlook.com>"]
edition = "2021"
description = "Diagnostics over Internet Protocol codec for client-server communication."
readme="README.md"
repository = "https://github.com/samp-reston/doip-codec"
license = "LICENSE.txt"
keywords = ["doip", "diagnostics", "vehicle", "codec"]
categories = ["simulation", "parser-implementations", "network-programming", "encoding"]

[dependencies]
futures = "0.3.31"
thiserror = "2.0.4"
tokio = { version = "1.42.0", features = ["full"] }
tokio-util = {version = "0.7.13", features = ["full"]}
